### ISSUE TITLE
Can't run logstash script.

### ISSUE THREAD

**Issue by sojjan1337** [zabbix/community-templates#58]
1. Added template logstash/6.0/ into Zabbix6

2. Then follows "fredprod" guide.

3. Tried with python2 and python3

4. Using logstash-v6x.py from the linked guide. 

When i run the script locally on a logstash-server i get the following error:
And i can see the same result in zabbix GUI "logstash check"

`Traceback (most recent call last): File "./logstash.py", line 112, in <module> ret = LogstashServer().run() File "/usr/lib/python2.7/site-packages/protobix/sampleprobe.py", line 281, in run self.zbx_config = self._init_config() File "/usr/lib/python2.7/site-packages/protobix/sampleprobe.py", line 204, in _init_config zbx_config = ZabbixAgentConfig(self.options.config_file) File "/usr/lib/python2.7/site-packages/protobix/zabbixagentconfig.py", line 56, in __init__ tmp_config = configobj.ConfigObj(config_file, list_values=False) File "/usr/lib/python2.7/site-packages/configobj.py", line 1229, in __init__ self._load(infile, configspec) File "/usr/lib/python2.7/site-packages/configobj.py", line 1318, in _load raise error configobj.DuplicateError: Duplicate keyword name at line 16.`

**Comment by sojjan1337** [comment]
Couldn't run them at the same time: 

Using only "update-items"

UserParameter=logstash.check,/usr/local/bin/logstash.py --update-items UserParameter=logstash.discovery,/usr/local/bin/logstash.py --discovery
